name: CI

on: [push]
    
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   # Runs every day at noon
  #   - cron: '0 12 * * *'
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.13.3 

      - name: Run a one-line script
        run: echo Hello, world!
      - name: install dependencies
        run: |
          make install
      - name: pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make install
      - name: Format code
        run: |
          make format
        
      
